<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DBModel_Cmscatlist', 'doctrine');

/**
 * DBModel_Base_Cmscatlist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cmscatid
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class DBModel_Base_Cmscatlist extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('v9_cmscatlist');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('cmscatid', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}