<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DBModel_Faq', 'doctrine');

/**
 * DBModel_Base_Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $q
 * @property text $a
 * @property datetime $post_time
 * @property datetime $update_time
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class DBModel_Base_Faq extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('v9_faq');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('q', 'text', 2000, array(
             'type' => 'text',
             'length' => '2000',
             ));
        $this->hasColumn('a', 'text', 2000, array(
             'type' => 'text',
             'length' => '2000',
             ));
        $this->hasColumn('post_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('update_time', 'datetime', null, array(
             'type' => 'datetime',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}