<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DBModel_GovPublicCat', 'doctrine');

/**
 * DBModel_Base_GovPublicCat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $GovPublic
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class DBModel_Base_GovPublicCat extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('v9_govpubliccat');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DBModel_GovPublic as GovPublic', array(
             'local' => 'id',
             'foreign' => 'catid'));
    }
}