<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DBModel_GovPublic', 'doctrine');

/**
 * DBModel_Base_GovPublic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property text $content
 * @property datetime $post_time
 * @property datetime $update_time
 * @property string $author
 * @property integer $department_id
 * @property integer $user_id
 * @property integer $is_public
 * @property integer $catid
 * @property DBModel_User $User
 * @property DBModel_Department $Department
 * @property DBModel_GovPublicCat $GovPublicCat
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class DBModel_Base_GovPublic extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('v9_govpublic');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('content', 'text', 5000, array(
             'type' => 'text',
             'length' => '5000',
             ));
        $this->hasColumn('post_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('update_time', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('author', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('department_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_public', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
        $this->hasColumn('catid', 'integer', 10, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '10',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DBModel_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('DBModel_Department as Department', array(
             'local' => 'department_id',
             'foreign' => 'id'));

        $this->hasOne('DBModel_GovPublicCat as GovPublicCat', array(
             'local' => 'catid',
             'foreign' => 'id'));
    }
}