<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DBModel_Note', 'doctrine');

/**
 * DBModel_Base_Note
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property text $content
 * @property datetime $post_time
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class DBModel_Base_Note extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('v9_note');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('content', 'text', 5000, array(
             'type' => 'text',
             'length' => '5000',
             ));
        $this->hasColumn('post_time', 'datetime', null, array(
             'type' => 'datetime',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}